#!/bin/bash
HERE=`pwd`
cd inputmaster/code
pio run
cp .pioenvs/nanoatmega328/firmware.hex $HERE/inputmaster_firmware_nano328.hex
cp .pioenvs/megaatmega2560/firmware.hex $HERE/inputmaster_firmware_mega2560.hex
cd $HERE/outputmaster/code
pio run
cp .pioenvs/nanoatmega328/firmware.hex $HERE/outputmaster_firmware_nano328.hex
cp .pioenvs/megaatmega2560/firmware.hex $HERE/outputmaster_firmware_mega2560.hex
cd $HERE

git add *firmware*.hex
